### PR TITLE
Add き as masu stem for 来る (closes #59)

### LINKED ISSUE #59: Add き as masu stem for 来る
The 連用形 for 来る is き (e.g. see [国語の文法](https://www.kokugobunpou.com/%E7%94%A8%E8%A8%80/%E5%8B%95%E8%A9%9E-7-%E3%82%AB%E8%A1%8C%E5%A4%89%E6%A0%BC%E6%B4%BB%E7%94%A8-%E3%82%B5%E8%A1%8C%E5%A4%89%E6%A0%BC%E6%B4%BB%E7%94%A8/)) but the [deinflect data](https://github.com/birtles/rikaichamp/blob/master/src/deinflect.ts#L351-L352) only recognizes き as a masu stem for words ending in きる and く.

### PR DESCRIPTION
**Pull request by ispedals**
It's as easy this, right?

### CODE REVIEW

**Comment by birtles** [comment]
Yep, it's that easy. We should keep the list sorted though. Do you mind doing that? (If not, I'll update the patch.)

**Comment by birtles** [comment]
Oh, and for any changes to `deinflect.ts` I've been adding a test to either `__tests__/deinflect.ts` or `__tests__/data.ts` too to make sure we don't regress it.

**Comment by ispedals** [comment]
I'll add test and rebase the commit after #62 is merged to make merging cleaner.

**Comment by ispedals** [comment]
Should be all set now

**Comment by birtles** [comment]
Thank you!

**Pull request merged**
