### PR TITLE
Parse ぬ form (closes #56)

### LINKED ISSUE #56: Parse ぬ form (打ち消し)
For example, today's asahi.com has a headline: 驚異の身体能力、飾らぬ人柄
Likewise 見ぬが仏、聞かぬが花 and similar variants.
Need to include する → せぬ and くる → こぬ.

### PR DESCRIPTION
**Pull request by ispedals**
I'm not sure about the Japanese localization,  but I followed the same pattern as -zu.

### CODE REVIEW

**Comment by birtles** [comment]
Thanks for doing this. As with the other PR, it would be good to keep the list sorted and add tests too.

Regarding the localization, I was intending to just report this as `deinflect_negative` (i.e. same as ない).

**Comment by birtles** [comment]
That is, I would re-use the same reason: `DeinflectReason.Negative`. I don't think there's any need to distinguish between the two forms.

**Comment by ispedals** [comment]
I've added the test, and used the negative reason. For sorting the deinflect rules,  are you sorting by len(field 1) desc, field 1 asc, field 2 asc? That's what it looks like it's sorted by, but then there are few entries out of place if this is the rule.

**Comment by birtles** [comment]
This is excellent. Thank you!

Regarding the sort order, it comes from the old rikaikun `deinflect.dat` file which I've massaged in various ways over time. It's possible I messed it up, or perhaps it was wrong to begin with.

**Pull request merged**
